import type {
  Brand,
  Category,
  Order,
  Product,
  Profile,
  ShippingZone,
  WalkInSale,
} from "@/lib/types";

export const categories: Category[] = [
  {
    id: "cat-phones",
    name: "Phone Accessories",
    slug: "phone-accessories",
    description: "Chargers, earbuds, cases, power banks, and daily mobile essentials.",
    hero: "Fast-charge gear, premium audio, and accessories that travel well.",
  },
  {
    id: "cat-computers",
    name: "Computer Accessories",
    slug: "computer-accessories",
    description: "Productivity upgrades for workstations, creators, and hybrid offices.",
    hero: "Cables, docks, keyboards, and monitor gear built for long sessions.",
  },
  {
    id: "cat-gaming",
    name: "Gaming Accessories",
    slug: "gaming-accessories",
    description: "Responsive controllers, RGB setup gear, and immersive audio.",
    hero: "Performance-first accessories for console and PC players.",
  },
  {
    id: "cat-home",
    name: "Home Appliances",
    slug: "home-appliances",
    description: "Compact appliances and smart home helpers for modern living.",
    hero: "Reliable essentials for kitchens, bedrooms, and shared spaces.",
  },
];

export const brands: Brand[] = [
  { id: "brand-anker", name: "Anker", slug: "anker" },
  { id: "brand-logitech", name: "Logitech", slug: "logitech" },
  { id: "brand-havit", name: "Havit", slug: "havit" },
  { id: "brand-oraimo", name: "Oraimo", slug: "oraimo" },
  { id: "brand-binatone", name: "Binatone", slug: "binatone" },
];

export const products: Product[] = [
  {
    id: "prod-powerbank",
    slug: "oraimo-travel-powerbank-20000mah",
    name: "Oraimo Travel Powerbank 20000mAh",
    shortDescription: "Slim high-capacity power bank with dual fast-charge output.",
    description:
      "A dependable 20000mAh backup battery for phones, earbuds, and small devices. Built for commuters, students, and creators who need all-day power without carrying a bulky brick.",
    categoryId: "cat-phones",
    brandId: "brand-oraimo",
    basePrice: 36000,
    costPrice: 24000,
    featured: true,
    status: "active",
    compatibility: ["USB-C", "iPhone", "Android", "Earbuds"],
    specs: [
      { label: "Capacity", value: "20000mAh" },
      { label: "Output", value: "22.5W fast charge" },
      { label: "Ports", value: "USB-C + Dual USB-A" },
    ],
    tags: ["fast charge", "travel", "best seller"],
    seoTitle: "Oraimo Travel Powerbank 20000mAh | Libsystem Accessories",
    seoDescription: "Buy the Oraimo 20000mAh powerbank with fast charging and travel-friendly design.",
    rating: 4.8,
    reviewCount: 124,
    images: [
      {
        id: "img-powerbank-1",
        url: "https://images.unsplash.com/photo-1587033411391-5d9e51cce126?auto=format&fit=crop&w=1200&q=80",
        alt: "Travel power bank",
      },
    ],
    variants: [
      {
        id: "var-powerbank-black",
        sku: "ORA-PB-20K-BLK",
        name: "Black",
        attributes: { color: "Black" },
        stockQuantity: 14,
        price: 36000,
        costPrice: 24000,
      },
      {
        id: "var-powerbank-blue",
        sku: "ORA-PB-20K-BLU",
        name: "Blue",
        attributes: { color: "Blue" },
        stockQuantity: 9,
        price: 37000,
        costPrice: 24500,
      },
    ],
  },
  {
    id: "prod-charger",
    slug: "anker-65w-gan-wall-charger",
    name: "Anker 65W GaN Wall Charger",
    shortDescription: "Compact laptop-and-phone charger with USB-C Power Delivery.",
    description:
      "A desk-friendly GaN charger that powers MacBooks, Android phones, iPads, and USB-C accessories without overheating your workspace.",
    categoryId: "cat-phones",
    brandId: "brand-anker",
    basePrice: 54000,
    costPrice: 36000,
    featured: true,
    status: "active",
    compatibility: ["USB-C", "MacBook", "Android", "iPad"],
    specs: [
      { label: "Power", value: "65W USB-C PD" },
      { label: "Input", value: "100-240V" },
      { label: "Build", value: "GaN compact body" },
    ],
    tags: ["charging", "office", "premium"],
    seoTitle: "Anker 65W GaN Wall Charger | Libsystem Accessories",
    seoDescription: "Power laptops and phones with a compact Anker 65W GaN charger.",
    rating: 4.9,
    reviewCount: 89,
    images: [
      {
        id: "img-charger-1",
        url: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=1200&q=80",
        alt: "Wall charger",
      },
    ],
    variants: [
      {
        id: "var-charger-white",
        sku: "ANK-GAN65-WHT",
        name: "White",
        attributes: { color: "White" },
        stockQuantity: 11,
        price: 54000,
        costPrice: 36000,
      },
    ],
  },
  {
    id: "prod-keyboard",
    slug: "logitech-mx-mechanical-mini",
    name: "Logitech MX Mechanical Mini",
    shortDescription: "Low-profile mechanical keyboard for fast, quiet productivity.",
    description:
      "Designed for coders, writers, and operators who want precision and comfort in a compact premium keyboard with multi-device switching.",
    categoryId: "cat-computers",
    brandId: "brand-logitech",
    basePrice: 125000,
    costPrice: 86000,
    featured: true,
    status: "active",
    compatibility: ["Windows", "macOS", "Bluetooth", "USB-C"],
    specs: [
      { label: "Switch Type", value: "Tactile Quiet" },
      { label: "Connectivity", value: "Bluetooth + Logi Bolt" },
      { label: "Battery", value: "15 days with backlight" },
    ],
    tags: ["keyboard", "creator", "office"],
    seoTitle: "Logitech MX Mechanical Mini | Libsystem Accessories",
    seoDescription: "Premium low-profile keyboard for creators and workstation setups.",
    rating: 4.9,
    reviewCount: 41,
    images: [
      {
        id: "img-keyboard-1",
        url: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=1200&q=80",
        alt: "Mechanical keyboard",
      },
    ],
    variants: [
      {
        id: "var-keyboard-graphite",
        sku: "LOG-MXMM-GRA",
        name: "Graphite",
        attributes: { color: "Graphite", layout: "US" },
        stockQuantity: 5,
        price: 125000,
        costPrice: 86000,
      },
    ],
  },
  {
    id: "prod-dock",
    slug: "anker-8in1-usbc-dock",
    name: "Anker 8-in-1 USB-C Dock",
    shortDescription: "Docking station with HDMI, Ethernet, and fast data transfer.",
    description:
      "A clean desk upgrade for remote workers and creators connecting displays, storage, wired internet, and peripherals from one laptop port.",
    categoryId: "cat-computers",
    brandId: "brand-anker",
    basePrice: 78000,
    costPrice: 52000,
    featured: false,
    status: "active",
    compatibility: ["USB-C", "Windows", "macOS"],
    specs: [
      { label: "Ports", value: "8 total ports" },
      { label: "Video", value: "4K HDMI output" },
      { label: "Networking", value: "Gigabit Ethernet" },
    ],
    tags: ["dock", "hybrid work", "creator"],
    seoTitle: "Anker 8-in-1 USB-C Dock | Libsystem Accessories",
    seoDescription: "Connect displays, internet, and storage with one USB-C dock.",
    rating: 4.7,
    reviewCount: 32,
    images: [
      {
        id: "img-dock-1",
        url: "https://images.unsplash.com/photo-1625842268584-8f3296236761?auto=format&fit=crop&w=1200&q=80",
        alt: "USB-C dock",
      },
    ],
    variants: [
      {
        id: "var-dock-space",
        sku: "ANK-DOCK8-SLV",
        name: "Silver",
        attributes: { color: "Silver" },
        stockQuantity: 7,
        price: 78000,
        costPrice: 52000,
      },
    ],
  },
  {
    id: "prod-headset",
    slug: "havit-rgb-gaming-headset",
    name: "Havit RGB Gaming Headset",
    shortDescription: "Comfort-fit gaming headset with surround sound staging.",
    description:
      "Immersive audio and a padded design built for long game nights, streaming sessions, and multiplayer calls.",
    categoryId: "cat-gaming",
    brandId: "brand-havit",
    basePrice: 42000,
    costPrice: 28000,
    featured: true,
    status: "active",
    compatibility: ["PC", "PS5", "Xbox", "3.5mm"],
    specs: [
      { label: "Microphone", value: "Noise-reducing boom mic" },
      { label: "Lighting", value: "RGB earcup accent" },
      { label: "Connection", value: "3.5mm + USB power" },
    ],
    tags: ["gaming", "audio", "rgb"],
    seoTitle: "Havit RGB Gaming Headset | Libsystem Accessories",
    seoDescription: "Comfortable gaming headset with immersive sound and RGB style.",
    rating: 4.6,
    reviewCount: 58,
    images: [
      {
        id: "img-headset-1",
        url: "https://images.unsplash.com/photo-1612444530582-fc66183b16f7?auto=format&fit=crop&w=1200&q=80",
        alt: "Gaming headset",
      },
    ],
    variants: [
      {
        id: "var-headset-black",
        sku: "HAV-HS-RGB-BLK",
        name: "Black",
        attributes: { color: "Black" },
        stockQuantity: 18,
        price: 42000,
        costPrice: 28000,
      },
    ],
  },
  {
    id: "prod-controller",
    slug: "havit-wireless-controller-pro",
    name: "Havit Wireless Controller Pro",
    shortDescription: "Responsive wireless controller with textured grip.",
    description:
      "A reliable controller for couch gaming and PC sessions, tuned for battery life and accurate trigger response.",
    categoryId: "cat-gaming",
    brandId: "brand-havit",
    basePrice: 47000,
    costPrice: 31500,
    featured: false,
    status: "active",
    compatibility: ["PC", "Android", "Console"],
    specs: [
      { label: "Battery", value: "12-hour play time" },
      { label: "Connection", value: "Bluetooth 5.0" },
      { label: "Feedback", value: "Dual vibration motors" },
    ],
    tags: ["controller", "wireless"],
    seoTitle: "Havit Wireless Controller Pro | Libsystem Accessories",
    seoDescription: "Wireless gaming controller with responsive triggers and long battery life.",
    rating: 4.5,
    reviewCount: 29,
    images: [
      {
        id: "img-controller-1",
        url: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=1200&q=80",
        alt: "Gaming controller",
      },
    ],
    variants: [
      {
        id: "var-controller-blue",
        sku: "HAV-CTRL-PRO-BLU",
        name: "Blue",
        attributes: { color: "Blue" },
        stockQuantity: 6,
        price: 47000,
        costPrice: 31500,
      },
    ],
  },
  {
    id: "prod-kettle",
    slug: "binatone-smart-electric-kettle",
    name: "Binatone Smart Electric Kettle",
    shortDescription: "Fast-boil kettle with auto shut-off and compact counter profile.",
    description:
      "A dependable kitchen essential for fast breakfasts, hostel living, and compact family spaces.",
    categoryId: "cat-home",
    brandId: "brand-binatone",
    basePrice: 31500,
    costPrice: 21000,
    featured: true,
    status: "active",
    compatibility: ["220-240V"],
    specs: [
      { label: "Capacity", value: "1.7L" },
      { label: "Finish", value: "Stainless steel" },
      { label: "Safety", value: "Auto shut-off" },
    ],
    tags: ["home", "kitchen", "essential"],
    seoTitle: "Binatone Smart Electric Kettle | Libsystem Accessories",
    seoDescription: "Fast-boil electric kettle for homes, offices, and hostels.",
    rating: 4.4,
    reviewCount: 63,
    images: [
      {
        id: "img-kettle-1",
        url: "https://images.unsplash.com/photo-1604335399105-a0c585fd81a1?auto=format&fit=crop&w=1200&q=80",
        alt: "Electric kettle",
      },
    ],
    variants: [
      {
        id: "var-kettle-silver",
        sku: "BIN-KET-17L-SLV",
        name: "Silver",
        attributes: { color: "Silver" },
        stockQuantity: 12,
        price: 31500,
        costPrice: 21000,
      },
    ],
  },
  {
    id: "prod-blender",
    slug: "binatone-compact-blender-2in1",
    name: "Binatone Compact Blender 2-in-1",
    shortDescription: "Compact kitchen blender for smoothies, sauces, and prep work.",
    description:
      "A sturdy countertop blender sized for apartments and family kitchens, with enough power for daily blending and meal prep.",
    categoryId: "cat-home",
    brandId: "brand-binatone",
    basePrice: 68000,
    costPrice: 47000,
    featured: false,
    status: "active",
    compatibility: ["220-240V"],
    specs: [
      { label: "Motor", value: "500W" },
      { label: "Jar", value: "1.5L" },
      { label: "Functions", value: "Blend + pulse" },
    ],
    tags: ["appliance", "kitchen"],
    seoTitle: "Binatone Compact Blender 2-in-1 | Libsystem Accessories",
    seoDescription: "Compact blender for smoothies and kitchen prep.",
    rating: 4.3,
    reviewCount: 21,
    images: [
      {
        id: "img-blender-1",
        url: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?auto=format&fit=crop&w=1200&q=80",
        alt: "Kitchen blender",
      },
    ],
    variants: [
      {
        id: "var-blender-charcoal",
        sku: "BIN-BLD-2IN1-CHR",
        name: "Charcoal",
        attributes: { color: "Charcoal" },
        stockQuantity: 4,
        price: 68000,
        costPrice: 47000,
      },
    ],
  },
];

export const profiles: Profile[] = [
  {
    id: "profile-admin-1",
    fullName: "Adaeze Okafor",
    email: "owner@libsystem.ng",
    phone: "+234 803 000 0001",
    role: "admin",
  },
  {
    id: "profile-staff-1",
    fullName: "Samuel James",
    email: "sales@libsystem.ng",
    phone: "+234 803 000 0002",
    role: "staff",
  },
  {
    id: "profile-customer-1",
    fullName: "Kene Nwosu",
    email: "kene@example.com",
    phone: "+234 803 210 4587",
    role: "customer",
  },
];

export const shippingZones: ShippingZone[] = [
  {
    id: "zone-lagos",
    name: "Lagos Mainland",
    regions: ["Ikeja", "Yaba", "Surulere", "Gbagada"],
    fee: 3500,
    eta: "Same day",
  },
  {
    id: "zone-island",
    name: "Lagos Island",
    regions: ["Lekki", "Victoria Island", "Ajah"],
    fee: 5000,
    eta: "Next day",
  },
  {
    id: "zone-nationwide",
    name: "Nationwide",
    regions: ["Abuja", "Port Harcourt", "Ibadan", "Other cities"],
    fee: 7500,
    eta: "2-4 business days",
  },
];

export const orders: Order[] = [
  {
    id: "order-1",
    orderNumber: "LS-240501",
    customerId: "profile-customer-1",
    customerName: "Kene Nwosu",
    customerEmail: "kene@example.com",
    customerPhone: "+234 803 210 4587",
    status: "in_transit",
    channel: "online",
    paymentMethod: "card",
    paymentReference: "PSK_REF_240501",
    fulfillmentMethod: "delivery",
    shippingZoneId: "zone-island",
    shippingAddress: "12 Admiralty Way, Lekki Phase 1, Lagos",
    subtotal: 90000,
    shippingFee: 5000,
    total: 95000,
    placedAt: "2026-05-01T10:30:00.000Z",
    items: [
      {
        id: "order-item-1",
        productId: "prod-powerbank",
        productName: "Oraimo Travel Powerbank 20000mAh",
        variantId: "var-powerbank-black",
        variantName: "Black",
        quantity: 1,
        unitPrice: 36000,
        unitCost: 24000,
        imageUrl: "https://images.unsplash.com/photo-1587033411391-5d9e51cce126?auto=format&fit=crop&w=1200&q=80",
      },
      {
        id: "order-item-2",
        productId: "prod-headset",
        productName: "Havit RGB Gaming Headset",
        variantId: "var-headset-black",
        variantName: "Black",
        quantity: 1,
        unitPrice: 42000,
        unitCost: 28000,
        imageUrl: "https://images.unsplash.com/photo-1612444530582-fc66183b16f7?auto=format&fit=crop&w=1200&q=80",
      },
      {
        id: "order-item-3",
        productId: "prod-controller",
        productName: "Havit Wireless Controller Pro",
        variantId: "var-controller-blue",
        variantName: "Blue",
        quantity: 1,
        unitPrice: 12000,
        unitCost: 9000,
        imageUrl: "https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=1200&q=80",
      },
    ],
  },
  {
    id: "order-2",
    orderNumber: "LS-240502",
    customerName: "Ifeoma Daniels",
    customerEmail: "ifeoma@example.com",
    customerPhone: "+234 803 555 1023",
    status: "completed",
    channel: "online",
    paymentMethod: "bank_transfer",
    paymentReference: "PSK_REF_240502",
    fulfillmentMethod: "pickup",
    subtotal: 54000,
    shippingFee: 0,
    total: 54000,
    placedAt: "2026-05-02T15:10:00.000Z",
    items: [
      {
        id: "order-item-4",
        productId: "prod-charger",
        productName: "Anker 65W GaN Wall Charger",
        variantId: "var-charger-white",
        variantName: "White",
        quantity: 1,
        unitPrice: 54000,
        unitCost: 36000,
        imageUrl: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=1200&q=80",
      },
    ],
  },
  {
    id: "order-3",
    orderNumber: "LS-240503",
    customerName: "Daniel Ojo",
    customerEmail: "daniel@example.com",
    customerPhone: "+234 806 333 9901",
    status: "paid",
    channel: "online",
    paymentMethod: "card",
    paymentReference: "PSK_REF_240503",
    fulfillmentMethod: "delivery",
    shippingZoneId: "zone-lagos",
    shippingAddress: "22 Herbert Macaulay, Yaba, Lagos",
    subtotal: 125000,
    shippingFee: 3500,
    total: 128500,
    placedAt: "2026-05-03T17:25:00.000Z",
    items: [
      {
        id: "order-item-5",
        productId: "prod-keyboard",
        productName: "Logitech MX Mechanical Mini",
        variantId: "var-keyboard-graphite",
        variantName: "Graphite",
        quantity: 1,
        unitPrice: 125000,
        unitCost: 86000,
        imageUrl: "https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=1200&q=80",
      },
    ],
  },
];

export const walkInSales: WalkInSale[] = [
  {
    id: "walk-1",
    receiptNumber: "WK-240501",
    recordedBy: "profile-staff-1",
    customerName: "Amina Bello",
    customerPhone: "+234 812 220 1122",
    paymentMethod: "cash",
    soldAt: "2026-05-01T13:10:00.000Z",
    subtotal: 73000,
    total: 73000,
    items: [
      {
        id: "walk-item-1",
        productId: "prod-kettle",
        productName: "Binatone Smart Electric Kettle",
        variantId: "var-kettle-silver",
        variantName: "Silver",
        quantity: 1,
        unitPrice: 31500,
        unitCost: 21000,
      },
      {
        id: "walk-item-2",
        productId: "prod-powerbank",
        productName: "Oraimo Travel Powerbank 20000mAh",
        variantId: "var-powerbank-blue",
        variantName: "Blue",
        quantity: 1,
        unitPrice: 37000,
        unitCost: 24500,
      },
      {
        id: "walk-item-3",
        productId: "prod-controller",
        productName: "Havit Wireless Controller Pro",
        variantId: "var-controller-blue",
        variantName: "Blue",
        quantity: 1,
        unitPrice: 4500,
        unitCost: 3000,
      },
    ],
  },
  {
    id: "walk-2",
    receiptNumber: "WK-240504",
    recordedBy: "profile-staff-1",
    paymentMethod: "pos",
    soldAt: "2026-05-04T11:45:00.000Z",
    subtotal: 114000,
    total: 114000,
    items: [
      {
        id: "walk-item-4",
        productId: "prod-headset",
        productName: "Havit RGB Gaming Headset",
        variantId: "var-headset-black",
        variantName: "Black",
        quantity: 2,
        unitPrice: 42000,
        unitCost: 28000,
      },
      {
        id: "walk-item-5",
        productId: "prod-powerbank",
        productName: "Oraimo Travel Powerbank 20000mAh",
        variantId: "var-powerbank-black",
        variantName: "Black",
        quantity: 1,
        unitPrice: 30000,
        unitCost: 22000,
      },
    ],
  },
];
